### ISSUE TITLE
Role based access

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#1]
besoin de pouvoir gérer les rôles (DDO, DDT, DDC, DDF) à plusieurs échelons (départemental et local)

**Comment by Loustik** [comment]
Reste le tuto et lister les rôles

**Comment by Loustik** [comment]
Reste à gérer l'affichage d'une erreur lorsqu'on utilise une permission qui n'existe pas. Aujourd'hui ça part dans le log. @bpasek t'en penses quoi?

**Comment by bpasek** [comment]
Eh bien.
Il faut que le menu n'offre que les actions dont on a le droit.
Si on en a pas le droit pas d'affichage.
Si on force l'URL, on renvoi une déconnexion.

**Comment by Loustik** [comment]
Au lieu du Check() tu as le Enforce() qui te renvoie vers une 403 si tu n'as pas le droit

**Comment by Loustik** [comment]
Marge ma Poule Rikouèste !
