### ISSUE TITLE
Faire fonctionner le site sur une autre base_URL

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#137]
Question à @bpasek  : si le site migre vers un truc du style `http://intranet.mondomaine.com` c'est que derrière il y a `http://mondomaine.com/intranet` par exemple. Mais ça change toutes les URLs... Là où nous on pointe vers du localhost/mapage.php ça ne marchera plus du coup... Il faudrait revoir tous les formulaires envoyés, et les liens directs (menus). Ton avis?

**Comment by bpasek** [comment]
Je ne comprends pas la question.
On est censé avoir tout fait en relatif non ?

**Comment by Loustik** [comment]
en fait ça devrait marcher puisqu'on fera un lien 'intranet.protectioncivile92.org'
