### ISSUE TITLE
GestionDPS PDF generation

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#14]
- [x] Template de base
- [ ] Certificat Original d'Affiliation
- [x] Déclaration à la Préfecture

**Comment by bpasek** [comment]
- [ ] Séparation Header / container / footer

- [ ] dynamisation des éléments

**Comment by Loustik** [comment]
@bpasek J'attends de toi que tu fasses ça par une fonction qui prend en entrée un numéro d'ID de DPS (pas le n° de certificat). En sortie, tu as le PDF généré. 

Par une autre méthode, tu l'envoies au navigateur.
