### ISSUE TITLE
Bug génération PDF

### ISSUE THREAD

**Issue by bpasek** [ProtectionCivile/intranet-protection-civile#180]
A l'autorisation d'un DPS :>

Fatal error: Uncaught Error: Call to a member function getTranslation() on string in /homepages/6/d601309969/htdocs/intranet-protection-civile/www/functions/pdf/build-pdf-dps-recap.php:15 Stack trace: #0 /homepages/6/d601309969/htdocs/intranet-protection-civile/www/functions/controller/dps-workflow-controller.php(153): buildPdfForDps('documents_dps/2...', Array) 

#1 /homepages/6/d601309969/htdocs/intranet-protection-civile/www/dps-view.php(30): require_once('/homepages/6/d6...') 

#2 {main} thrown in /homepages/6/d601309969/htdocs/intranet-protection-civile/www/functions/pdf/build-pdf-dps-recap.php on line 15
  
#2 /Users/nicolas/GitHub/intranet-protection-civile/www/web.php(30): include('/Users/nicolas/...')

#3 {main}
  thrown in /Users/nicolas/GitHub/intranet-protection-civile/www/functions/pdf/build-pdf-dps-recap.php on line 15

**Comment by Loustik** [comment]
@bpasek c'était en faisant quoi?

**Comment by bpasek** [comment]
En validant le DPS

**Comment by Loustik** [comment]
reproduit

**Comment by Loustik** [comment]
Corrigé partiellement. Autre bug découvert : quand no souhaite valider un poste DDO sans convention ni RIS, sans aucun document. Le répertoire de destination n'existe pas et on n'arrive pas à créer la déclaration (FPDF error: Unable to create output file: documents_dps/2015/COU/006/92-15-COU-006-DECL.pdf).

Il faut externaliser la création des répertoires et l'appeler lors de la création de la DECL

**Comment by Loustik** [comment]
Non, empêcher la validation du poste même si pas de document. Tant pis pour toi Pascal :)

**Comment by Loustik** [comment]
fait comme tel
