### ISSUE TITLE
[TOOL] Librairie de chargement de configuration

### ISSUE THREAD

**Issue by jean-pasqualini** [ProtectionCivile/intranet-protection-civile#22]
Je vous propose de vous apporter une librairie de chargement de configuration.

**Points clé,**
- Reconnait les formats (.ini, .json, .php)
- Elle tient en 1 seul fichier
- Pas de dépendances
- Performante (mise en cache apc)

**Example d'utilisation,**

`<?php $config = lib\conf\conf_load_configuration_file('maconfiguration', __DIR__); ?>`

Je vous invite à voter pour ou contre son intégration dans le projet.

Jean

**Comment by jean-pasqualini** [comment]
@Loustik @bpasek

**Comment by bpasek** [comment]
Pour moi, oui, et toi @Loustik ?

**Comment by Loustik** [comment]
100% partant, c’est une excellente idée !!

ça ajoute un peu de flexibilité au projet !

Désolé du retard, nous étions en mission.
