### ISSUE TITLE
GestionDPS: Pouvoir sélectionner soi-même le type de DPS lors de la demande

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#65]
override RIS calculation

**Comment by bpasek** [comment]
Le système doit-il brider les ME et GE selon les droits ?

**Comment by Loustik** [comment]
Noooon, on ne va pas s'emmerder pour ça, il faut rester simple et fonctionnel. Au besoin il y aura une demande d'évol

**Comment by bpasek** [comment]
Par-fait.

**Comment by Loustik** [comment]
Et l'afficher dans le listing

**Comment by Loustik** [comment]
C'est fait.
