### ISSUE TITLE
GestionDPS: Moyens fournis par les parties

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#68]
a séparer dans la demande de dps

**Comment by Loustik** [comment]
inclure aussi le nombre de lot A, B, C fournis par la PC

**Comment by Loustik** [comment]
mettre le nombre de DSA aussi (de la PC)

**Comment by Loustik** [comment]
L'orga peut fournir des tentes / local / moyens autres

**Comment by bpasek** [comment]
Prévoir un champ libre ? "textarea" ?

**Comment by Loustik** [comment]
C'est déjà le cas, je l'ai déjà mis en place la partie "moyens fournis par l'organisateur".  Ne reste qu'a rajouter les 3 lots et le DSA dans la partie des moyens fournis par la PC

**Comment by Loustik** [comment]
Fait !
