### ISSUE TITLE
GestionDPS: Le calcul de RIS n'est pas bon

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#71]
genre quand y'a pas besoin de secours, ça affiche PAPS

**Comment by bpasek** [comment]
A vérifier, mais dans les conditions d'affichage, il doit y avoir un min PAPS.
Après, est-ce nécessaire ? Car en dessous du PAPS l'utilisation de la fonction est inutile.

**Comment by Loustik** [comment]
Il faut juste vérifier le calcul. Mais sinon, OK pour laisser PAPS; sinon ça ne sert à rien de faire une demande de DPS ici.

**Comment by bpasek** [comment]
Ok pour faire une vérification

**Comment by Loustik** [comment]
C'est fait, tout est modifié :)
