### ISSUE TITLE
GestionDPS Horaires autoremplis

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#8]
Horaires du dispositifs forcément plus larges que les horaires de la manifestation

**Comment by bpasek** [comment]
Ca semble compliqué pour deux raisons 
1. compliqué de récupérer la valeur du datepicker
2. augmenter les tranches horaires demande une sacré gymnastique en algo... (je suis à l'écoute)

**Comment by Loustik** [comment]
### Fait et fonctionnel, et je suis allé encore plus loin : 
- la date de fin de l'évènement :
  - ne peut pas être antérieure à la date de début de l'évènement
- la date de fin du dispositif :
  - ne peut pas être antérieure à la date de début de l'évènement
  - ne peut pas être postérieure à la date de fin de l'évènement
  - est par défaut celle qui est positionnée comme date de fin de l'évenement
- l'heure de fin de l'évènement :
  - ne peut pas être antérieure à l'heure de début de l'évènement
- l'heure de fin du dispositif :
  - ne peut pas être antérieure à l'heure de début de l'évènement
  - ne peut pas être anttérieure à la date de fin de l'évènement (c'est là que c'est bien)
  - est par défaut 15 minutes après celle qui est positionnée comme heure de fin de l'évenement

même gymnastique pour les dates de début et les heures de début
