### ISSUE TITLE
GestionDPS: Fin d'ajout de DPS : que faire ?

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#84]
aujourd'hui il y a une redorerions vers la liste des DPS (qui ne marche pas). On peut soit : 
- la faire marcher
- proposer un bouton de retour vers le liste des DPS si pas d'erreur (implique de gérer les erreurs)

**Comment by bpasek** [comment]
C'est une régression ça.
Si tu arrives sur le infinite loader, c'est que tu as un bug.
Le problème des headers est un paramètre envoyé : d'ailleurs tu as la ligne qui indique le paramètre déjà envoyé.

**Comment by Loustik** [comment]
Okay. Problème réglé autrement
<img width="654" alt="temp" src="https://user-images.githubusercontent.com/11842340/28566167-a3066662-712e-11e7-9adb-92305c2a3038.png">
