### ISSUE TITLE
GestionDPS: Validateurs (client et serveur) non-fonctionnels

### ISSUE THREAD

**Issue by Loustik** [ProtectionCivile/intranet-protection-civile#85]
j'arrive à créer un DPS sans l'email du client

- normalement le validateur client ne doit pas soumettre le formulaire... maintenant il le fait

- normalement le validateur serveur ne devrait pas exécuter la query, et il le fait. Pourtant le message d'erreur affiché est le bon, et il provient du serveur.

**Comment by bpasek** [comment]
Peux-tu être plus précis ?
C'est sur le contrôle de surface le problème ?

**Comment by Loustik** [comment]
C'est fait. Quand on vient d'une création from scratch, ça marche en validation client. le pb était d'une duplication. Le client ne passe pas (normal, valeur non nulle mais remplie (html).

le validateur serveur marche maintenant
